"""add_level_source_to_audit_logs

Revision ID: 733fd949e72e
Revises: a09ef291a4e4
Create Date: 2026-04-04 11:29:18.591264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733fd949e72e'
down_revision: Union[str, Sequence[str], None] = 'a09ef291a4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
