"""initial_schema

Revision ID: 9c1abd88978b
Revises: 
Create Date: 2026-04-03 17:42:51.792792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1abd88978b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('immich_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_created_at', sa.DateTime(), nullable=True),
    sa.Column('file_modified_at', sa.DateTime(), nullable=True),
    sa.Column('local_date_time', sa.DateTime(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_trashed', sa.Boolean(), nullable=True),
    sa.Column('is_external_library', sa.Boolean(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('camera_make', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('album_ids_json', sa.JSON(), nullable=True),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_immich_id'), ['immich_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('job_run_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_job_run_id'), ['job_run_id'], unique=False)

    op.create_table('buckets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('mapping_mode', sa.String(), nullable=True),
    sa.Column('immich_album_id', sa.String(), nullable=True),
    sa.Column('classification_prompt', sa.Text(), nullable=True),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('negative_examples_json', sa.JSON(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buckets_name'), ['name'], unique=True)

    op.create_table('job_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('log_lines_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_status'), ['status'], unique=False)

    op.create_table('prompt_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('job_run_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('assembled_prompt_json', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_response_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_runs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_runs_job_run_id'), ['job_run_id'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('bucket_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_prompt_type'), ['prompt_type'], unique=False)

    op.create_table('provider_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('extra_config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_configs_provider_name'), ['provider_name'], unique=True)

    op.create_table('review_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('suggested_classification_id', sa.String(), nullable=True),
    sa.Column('suggested_metadata_id', sa.String(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('approved_bucket_id', sa.String(), nullable=True),
    sa.Column('approved_bucket_name', sa.String(), nullable=True),
    sa.Column('approved_description', sa.Text(), nullable=True),
    sa.Column('approved_tags_json', sa.JSON(), nullable=True),
    sa.Column('approved_subalbum', sa.String(), nullable=True),
    sa.Column('subalbum_approved', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('writeback_triggered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_asset_id'), ['asset_id'], unique=False)

    op.create_table('suggested_classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('suggested_bucket_id', sa.String(), nullable=True),
    sa.Column('suggested_bucket_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('subalbum_suggestion', sa.String(), nullable=True),
    sa.Column('review_recommended', sa.Boolean(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('prompt_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('override_bucket_id', sa.String(), nullable=True),
    sa.Column('override_bucket_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggested_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggested_classifications_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggested_classifications_status'), ['status'], unique=False)

    op.create_table('suggested_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('description_suggestion', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('approved_description', sa.Text(), nullable=True),
    sa.Column('approved_tags_json', sa.JSON(), nullable=True),
    sa.Column('writeback_status', sa.String(), nullable=True),
    sa.Column('writeback_error', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('prompt_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggested_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggested_metadata_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggested_metadata_asset_id'))

    op.drop_table('suggested_metadata')
    with op.batch_alter_table('suggested_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggested_classifications_status'))
        batch_op.drop_index(batch_op.f('ix_suggested_classifications_asset_id'))

    op.drop_table('suggested_classifications')
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_asset_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_provider_name'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_prompt_type'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('prompt_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_runs_job_run_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_runs_asset_id'))

    op.drop_table('prompt_runs')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_status'))
        batch_op.drop_index(batch_op.f('ix_job_runs_job_type'))

    op.drop_table('job_runs')
    with op.batch_alter_table('buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buckets_name'))

    op.drop_table('buckets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_job_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_asset_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_immich_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
